Sync skeleton files from solutions branch

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,148 +10,150 @@ jobs:
   test:
     if: ${{(github.repository == 'phewson/mthm503' && github.ref == 'refs/heads/python_private') || (github.repository != 'phewson/mthm503' && github.ref == 'refs/heads/main')}}
     runs-on: ubuntu-latest
+    env:
+      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Cache Conda environment
-        uses: actions/cache@v4
-        with:
-          path: /usr/share/miniconda3/envs/python-exercises
-          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
-          restore-keys: |
-            conda-${{ runner.os }}-
-
       - name: Set up Miniconda
-        uses: conda-incubator/setup-miniconda@v2
+        uses: conda-incubator/setup-miniconda@v3
         with:
           miniconda-version: 'latest'
+          mamba-version: "*"
+          use-mamba: true
           channels: conda-forge
           environment-file: environment.yml
           activate-environment: python-exercises
-          auto-activate-base: false
-          use-only-tar-bz2: true
 
-      - name: Set up Quarto
-        uses: quarto-dev/quarto-actions/setup@v2
-        with:
-          version: 1.4.550
-
+      # --- INTRO TOPIC ---
       - name: Run tests for intro topic
+        continue-on-error: true
+        id: intro_test
         run: |
-          conda run -n python-exercises pytest course/intro/tests --ignore=intro/tests/test_db_connection.py | fold -s -w 72 | tee intro_tests_output.txt
-          echo "${PIPESTATUS[0]}" > intro_tests_status.txt
+          conda run -n python-exercises pytest course/intro/tests --ignore=intro/tests/test_db_connection.py | tee intro_tests_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
 
-      - name: Run flake8 linter for intro topic
+      - name: Run flake8 for intro
+        continue-on-error: true
+        id: intro_lint
         run: |
-          echo "Running flake8..." | tee intro_flake8_output.txt
-          conda run -n python-exercises flake8 course/intro --exit-zero | fold -s -w 72 | tee -a intro_flake8_output.txt
-          echo "${PIPESTATUS[0]}" > intro_lint_status.txt
-          echo "flake8 completed at $(date)" | tee -a intro_flake8_output.txt
-        
-      - name: Run doit pipeline for intro topic
-        run: | 
-          conda run -n python-exercises doit -f dodo_ict_unsupervised.py | fold -s -w 72 | tee -a intro_pipeline_output.txt
-          echo "${PIPESTATUS[0]}" > intro_pipeline_status.txt
+          conda run -n python-exercises flake8 course/intro --exit-zero | tee intro_flake8_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
 
-      - name: Run pytest on regression if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
+      - name: Run pipeline for intro
+        continue-on-error: true
+        id: intro_dvc_demo
         run: |
-          conda run -n python-exercises pytest course/regression |  fold -s -w 72 | tee regression_tests_output.txt
-          echo "${PIPESTATUS[0]}" > regression_tests_status.txt
-          
-      - name: Run pytest on supervised if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
-        run: |
-          conda run -n python-exercises pytest course/supervised_classification |  fold -s -w 72 | tee supervised_tests_output.txt
-          echo "${PIPESTATUS[0]}" > supervised_tests_status.txt
-          
-      - name: Run pytest on unsupervised if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
-        run: |
-          conda run -n python-exercises pytest course/unsupervised_classification |  fold -s -w 72 | tee unsupervised_tests_output.txt
-          echo "${PIPESTATUS[0]}" > unsupervised_tests_status.txt
+          conda run -n python-exercises dvc repro intro_demo --exit-zero | tee intro_dvc_demo_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
 
-      - name: Run flake8 linter on regression if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
+      # --- REGRESSION ---
+      - name: Run tests for regression
+        continue-on-error: true
+        id: reg_test
         run: |
-          echo "Running flake8..." | tee regression_flake8_output.txt
-          conda run -n python-exercises flake8 course/regression --exit-zero | fold -s -w 72 | tee -a regression_flake8_output.txt
-          echo "${PIPESTATUS[0]}" > regression_lint_status.txt
-          echo "flake8 completed at $(date)" | tee -a regression_flake8_output.txt
-          
-      - name: Run flake8 linter on supervised if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
-        run: |
-          echo "Running flake8..." | tee supervised_flake8_output.txt
-          conda run -n python-exercises flake8 course/supervised_classification --exit-zero | fold -s -w 72 | tee -a supervised_flake8_output.txt
-          echo "${PIPESTATUS[0]}" > supervised_lint_status.txt
-          echo "flake8 completed at $(date)" | tee -a supervised_flake8_output.txt
-          
-      - name: Run flake8 linter on unsupervised if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
-        run: |
-          echo "Running flake8..." | tee unsupervised_flake8_output.txt
-          conda run -n python-exercises flake8 course/unsupervised_classification --exit-zero | fold -s -w 72 | tee -a unsupervised_flake8_output.txt
-          echo "${PIPESTATUS[0]}" > unsupervised_lint_status.txt
-          echo "flake8 completed at $(date)" | tee -a unsupervised_flake8_output.txt
-          
-      - name: Run flake8 linter on dodo files if COURSEWORK exists
-        if: ${{ hashFiles('COURSEWORK') != '' }}
-        run: |
-          echo "Running flake8..." | tee dodo_flake8_output.txt
-          conda run -n python-exercises flake8 dodo*.py --exit-zero | fold -s -w 72 | tee -a dodo_flake8_output.txt
-          echo "${PIPESTATUS[0]}" > dodo_lint_status.txt
-          echo "flake8 completed at $(date)" | tee -a dodo_flake8_output.txt
-        
-      - name: Generate PDF report
-        if: hashFiles('COURSEWORK') == ''
-        run: |
-          pip install pymupdf
-          python .github_ict_report.py
+          conda run -n python-exercises pytest course/regression | tee regression_tests_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
 
-      - name: Generate coursework test and lint
-        if: hashFiles('COURSEWORK') != ''
+      - name: Run flake8 for regression
+        continue-on-error: true
+        id: reg_lint
+        run: |
+          conda run -n python-exercises flake8 course/regression --exit-zero | tee regression_flake8_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+      # --- SUPERVISED ---
+      - name: Run tests for supervised
+        continue-on-error: true
+        id: sup_test
+        run: |
+          conda run -n python-exercises pytest course/supervised_classification | tee supervised_tests_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+      - name: Run flake8 for supervised
+        continue-on-error: true
+        id: sup_lint
+        run: |
+          conda run -n python-exercises flake8 course/supervised_classification --exit-zero | tee supervised_flake8_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+      # --- UNSUPERVISED ---
+      - name: Run tests for unsupervised
+        continue-on-error: true
+        id: unsup_test
+        run: |
+          conda run -n python-exercises pytest course/unsupervised_classification | tee unsupervised_tests_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+      - name: Run flake8 for unsupervised
+        continue-on-error: true
+        id: unsup_lint
+        run: |
+          conda run -n python-exercises flake8 course/unsupervised_classification --exit-zero | tee unsupervised_flake8_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+      - name: Run flake8 for scripts
+        continue-on-error: true
+        id: scripts
+        run: |
+          conda run -n python-exercises flake8 course/scripts/*/*.py --exit-zero | tee script_flake8_output.txt
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
+          
+      # --- SUMMARY DASHBOARD ---
+      - name: Generate Summary Dashboard
+        if: always()
+        run: |
+          function get_emoji() {
+            if [ "$1" == "0" ]; then echo "🟢 Pass"; 
+            elif [ "$1" == "" ]; then echo "🔴 Did not run";
+            else echo "🟠 Errors/Failures"; fi
+          }
+
+          echo "## 📊 Coursework Status Dashboard" >> $GITHUB_STEP_SUMMARY
+          echo "| Task | Status |" >> $GITHUB_STEP_SUMMARY
+          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Intro Tests** | $(get_emoji ${{ steps.intro_test.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Intro Lint** | $(get_emoji ${{ steps.intro_lint.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Intro DVC** | $(get_emoji ${{ steps.intro_dvc_demo.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Regression Tests** | $(get_emoji ${{ steps.reg_test.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Regression Lint** | $(get_emoji ${{ steps.reg_lint.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Supervised Tests** | $(get_emoji ${{ steps.sup_test.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Supervised Lint** | $(get_emoji ${{ steps.sup_lint.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Unsupervised Tests** | $(get_emoji ${{ steps.unsup_test.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Unsupervised Lint** | $(get_emoji ${{ steps.unsup_lint.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+          echo "| **Scripts Lint** | $(get_emoji ${{ steps.scripts.outputs.exit_code }}) |" >> $GITHUB_STEP_SUMMARY
+
+# --- PDF REPORT GENERATION ---
+      # We bring back your collation logic here
+      - name: Generate Collated PDF Reports
+        if: always()
         run: |
           pip install pymupdf
           python .github_cw_report.py
 
-      - name: Upload CI report PDF
+      - name: Upload CI Report and Artefacts
+        if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: actions_report
-          path: | 
+          name: full_coursework_report
+          path: |
             ci_report.pdf
-            vignettes/unsupervised/unsupervised_classification.html
-          
+            *_output.txt
 
-      - name: Evaluate intro topic results
+# --- FINAL EVALUATION ---
+      - name: Final Status Check
+        if: always()
         run: |
-          intro_status=$(cat intro_tests_status.txt)
-          intro_lint=$(cat intro_lint_status.txt)
-          intro_pipeline=$(cat intro_pipeline_status.txt)
-          if [ "$intro_status" -ne 0 ] || [ "$intro_lint" -ne 0 ] || [ "$intro_pipeline" -ne 0 ]; then
-            echo "Intro topic checks failed."
+          # This step actually fails the build if any status was non-zero 
+          # so they still get a 'Red X' on the commit, but only at the very end.
+          if [[ "${{ steps.intro_test.outputs.exit_code }}" != "0" || \
+                "${{ steps.reg_test.outputs.exit_code }}" != "0" || \
+                "${{ steps.sup_test.outputs.exit_code }}" != "0" || \
+                "${{ steps.unsup_test.outputs.exit_code }}" != "0" || \
+                "${{ steps.scripts.outputs.exit_code }}" != "0" ]]; then
+            echo "One or more tests failed. Please see your pdf for details"
             exit 1
-          else
-            echo "Intro topic checks passed."
           fi
-
-
-      - name: Evaluate results
-        if: ${{ hashFiles('COURSEWORK') != '' }}
-        run: |
-          regression_status=$(cat regression_tests_status.txt)
-          supervised_status=$(cat supervised_tests_status.txt)
-          unsupervised_status=$(cat unsupervised_tests_status.txt)
-          regression_lint=$(cat regression_lint_status.txt)
-          supervised_lint=$(cat supervised_lint_status.txt)
-          unsupervised_lint=$(cat unsupervised_lint_status.txt)
-
-          if [ "$regression_status" -ne 0 ] || [ "$supervised_status" -ne 0 ] || [ "$unsupervised_status" -ne 0 ] || \
-             [ "$regression_lint" -ne 0 ] || [ "$supervised_lint" -ne 0 ] || [ "$unsupervised_lint" -ne 0 ]; then
-            echo "One or more coursework checks failed."
-            exit 1
-          else
-            echo "All coursework checks passed."
-          fi
+  
